#!/usr/bin/env python3
"""
_plot_points_data.py — the Adventure Crafter Plot Points Table, hand-transcribed
from references/canon/The-Adventure-Crafter.md (the "Plot Points Table Reduced"
blocks). The PDF prints this as wrapped two-column text, so the clean names live
here verbatim rather than being machine-scraped. build_data.py consumes this and
verifies every Theme column covers 25-95 with no gaps/overlaps.

Each row: (name, ACT, TEN, MYS, SOC, PER).  "-" = no entry in that Theme column;
"a-b" or "a" = the d100 range in that column.  Structural rows (1-8 Conclusion,
9-24 None, 96-100 Meta) are added by build_data.py, not listed here.
"""
PLOT_POINTS = [
    # name,                                              ACT,     TEN,     MYS,     SOC,     PER
    ("Into The Unknown",                                  "-",   "25-26", "25-26",  "-",     "-"),
    ("A Character Is Attacked In A Non-Lethal Way",     "25-26",  "-",     "-",     "-",     "-"),
    ("A Needed Resource Runs Out",                        "-",   "27",     "-",     "-",     "-"),
    ("Useful Information From An Unknown Source",         "-",    "-",    "27-28",  "-",     "-"),
    ("Impending Doom",                                    "-",   "28",     "-",     "-",     "-"),
    ("Outcast",                                           "-",    "-",     "-",    "25-26",  "-"),
    ("Persuasion",                                        "-",    "-",     "-",     "-",    "25-26"),
    ("A Motive Free Crime",                               "-",   "29",    "29-30",  "-",     "-"),
    ("Collateral Damage",                                "27",   "30",     "-",     "-",     "-"),
    ("Shady Places",                                      "-",   "31-32",  "-",     "-",     "-"),
    ("A Character Is Attacked In A Lethal Way",         "28-29",  "-",     "-",     "-",     "-"),
    ("Do It, Or Else",                                    "-",   "33",     "-",     "-",    "27"),
    ("Remote Location",                                   "-",   "34",     "-",     "-",     "-"),
    ("Ambush",                                          "30-31",  "-",     "-",     "-",     "-"),
    ("Sold!",                                             "-",    "-",     "-",    "27-28",  "-"),
    ("Catastrophe",                                      "32",   "35",     "-",     "-",     "-"),
    ("Grisly Tone",                                       "-",   "36",     "-",     "-",     "-"),
    ("Character Has A Clever Idea",                      "33",    "-",     "-",     "-",     "-"),
    ("Something Is Getting Away",                        "34",   "37",     "-",     "-",     "-"),
    ("Retaliation",                                       "-",   "38-39",  "-",    "29-30", "28"),
    ("A Character Disappears",                            "-",   "40",    "31-32",  "-",     "-"),
    ("Hunted",                                          "35-36", "41",     "-",     "-",     "-"),
    ("A High Energy Gathering",                           "-",    "-",     "-",    "31",     "-"),
    ("A Rare Or Unique Social Gathering",                "-",    "-",     "-",    "32",     "-"),
    ("Bad Decision",                                      "-",   "42",     "-",     "-",    "29"),
    ("This Isn't Working",                                "-",    "-",    "33",     "-",     "-"),
    ("Distraction",                                      "37",    "-",     "-",     "-",     "-"),
    ("Ill Will",                                          "-",    "-",     "-",     "-",    "30-31"),
    ("An Organization",                                   "-",    "-",     "-",    "33-34",  "-"),
    ("Wanted By The Law",                                 "-",   "43",     "-",     "-",    "32-33"),
    ("A Resource Disappears",                             "-",    "-",    "34-35",  "-",     "-"),
    ("It Is Your Duty",                                   "-",    "-",     "-",     "-",    "34-35"),
    ("Fortuitous Find",                                   "-",    "-",    "36",     "-",     "-"),
    ("Character Connection Severed",                      "-",    "-",     "-",     "-",    "36-37"),
    ("All Is Revealed!",                                  "-",    "-",    "37",     "-",     "-"),
    ("Humiliation",                                       "-",    "-",     "-",     "-",    "38"),
    ("People Behaving Badly",                             "-",    "-",     "-",    "35",     "-"),
    ("Useful Information From A Known Source",            "-",    "-",    "38-39",  "-",     "-"),
    ("Cryptic Information From A Known Source",           "-",    "-",    "40",     "-",     "-"),
    ("Lie Discovered",                                    "-",    "-",    "41-42",  "-",     "-"),
    ("A Character Is Attacked To Abduct",               "38-39",  "-",     "-",     "-",     "-"),
    ("Something Exotic",                                "40",    "44",    "43",     "-",     "-"),
    ("Immediately",                                     "41-42", "45",     "-",     "-",     "-"),
    ("Fame",                                              "-",    "-",     "-",    "36",     "-"),
    ("Chase",                                           "43-44",  "-",     "-",     "-",     "-"),
    ("Betrayal!",                                         "-",   "46",     "-",     "-",    "39-40"),
    ("A Crime Is Committed",                              "-",    "-",    "44-45",  "-",     "-"),
    ("A Character Is Incapacitated",                      "-",   "47",     "-",     "-",    "41-42"),
    ("It's A Secret",                                     "-",    "-",    "46-47",  "-",     "-"),
    ("Something Lost Has Been Found",                     "-",    "-",    "48",     "-",     "-"),
    ("Scapegoat",                                         "-",    "-",     "-",    "37",     "-"),
    ("Nowhere To Run",                                    "-",   "48",     "-",     "-",     "-"),
    ("At Night",                                          "-",   "49-50",  "-",     "-",     "-"),
    ("The Observer",                                      "-",    "-",    "49",    "38",    "43"),
    ("Escape",                                          "45-46",  "-",     "-",     "-",     "-"),
    ("A Secret Weapon",                                   "-",   "51",    "50",     "-",     "-"),
    ("Heavily Guarded",                                 "47-48", "52",     "-",     "-",     "-"),
    ("Rescue",                                          "49-50",  "-",     "-",     "-",     "-"),
    ("Liar!",                                             "-",    "-",    "51-52", "39",     "-"),
    ("Home Sweet Home",                                   "-",    "-",     "-",     "-",    "44-45"),
    ("A Character Acts Out Of Character",                 "-",    "-",    "53",     "-",     "-"),
    ("Headquarters",                                      "-",    "-",     "-",    "40-41", "46"),
    ("Physical Contest Of Skills",                      "51-52",  "-",     "-",     "-",     "-"),
    ("Dead",                                              "-",   "53",    "54",     "-",     "-"),
    ("A Common Social Gathering",                         "-",    "-",     "-",    "42-43",  "-"),
    ("Light Urban Setting",                               "-",    "-",     "-",    "44-45",  "-"),
    ("Mystery Solved",                                    "-",    "-",    "55-56",  "-",     "-"),
    ("A Work Related Gathering",                          "-",    "-",     "-",    "46-47",  "-"),
    ("Family Matters",                                    "-",    "-",     "-",     "-",    "47-48"),
    ("Secret Information Leaked",                          "-",    "-",    "57",     "-",     "-"),
    ("Suspicion",                                         "-",   "54",    "58-59", "48",     "-"),
    ("Lose Lose",                                         "-",   "55",     "-",     "-",     "-"),
    ("A Figure From The Past",                            "-",    "-",     "-",     "-",    "49"),
    ("Mass Battle",                                     "53-54",  "-",     "-",     "-",     "-"),
    ("Out In The Open",                                   "-",   "56",     "-",     "-",     "-"),
    ("Evidence",                                          "-",    "-",    "60-61",  "-",     "-"),
    ("A Character Is Diminished",                         "-",   "57-58",  "-",     "-",    "50-51"),
    ("The Plot Thickens",                                 "-",    "-",    "62-63",  "-",     "-"),
    ("Enemies",                                           "-",   "59",     "-",    "49",    "52-53"),
    ("Dubious Rationale",                                 "-",    "-",    "64",     "-",     "-"),
    ("Menacing Tone",                                     "-",   "60",     "-",     "-",     "-"),
    ("A Crucial Life Support System Begins To Fail",   "55",    "61",    "65",     "-",     "-"),
    ("Dense Urban Setting",                               "-",    "-",     "-",    "50-51",  "-"),
    ("Doing The Right Thing",                             "-",    "-",     "-",     "-",    "54"),
    ("Victory!",                                        "56-57", "62",     "-",     "-",     "-"),
    ("Taking Chances",                                  "58-59", "63",     "-",     "-",     "-"),
    ("A Group Is In Trouble",                             "-",    "-",     "-",    "52-53",  "-"),
    ("Sole Survivor",                                   "60-61", "64",     "-",     "-",     "-"),
    ("Token Response",                                    "-",    "-",     "-",    "54",     "-"),
    ("Cryptic Information From An Unknown Source",        "-",    "-",    "66-67",  "-",     "-"),
    ("A Common Thread",                                   "-",    "-",    "68-69",  "-",     "-"),
    ("A Problem Returns",                                 "-",   "65-66",  "-",     "-",     "-"),
    ("Stuck",                                             "-",   "67-68",  "-",     "-",     "-"),
    ("At Your Mercy",                                     "-",    "-",     "-",     "-",    "55-56"),
    ("Stop That",                                       "62-63",  "-",     "-",     "-",     "-"),
    ("Not Their Master",                                  "-",    "-",    "70",    "55",     "-"),
    ("Fall From Power",                                   "-",    "-",     "-",     "-",    "57-58"),
    ("Help Is Offered, For A Price",                      "-",    "-",     "-",     "-",    "59-60"),
    ("Public Location",                                   "-",    "-",     "-",    "56-57",  "-"),
    ("The Leader",                                        "-",    "-",     "-",    "58-59",  "-"),
    ("Prized Possession",                                 "-",    "-",     "-",     "-",    "61-62"),
    ("Savior",                                            "-",    "-",     "-",    "60-61",  "-"),
    ("Disarmed",                                          "-",   "69-70",  "-",     "-",    "63"),
    ("The Secret To The Power",                           "-",    "-",    "71-72",  "-",     "-"),
    ("Hidden Agenda",                                     "-",    "-",    "73-74",  "-",     "-"),
    ("Defend Or Not To Defend",                         "64-65",  "-",     "-",     "-",     "-"),
    ("Crash",                                           "66-67",  "-",     "-",     "-",     "-"),
    ("Reinforcements",                                    "-",    "-",     "-",    "62-63",  "-"),
    ("Government",                                         "-",    "-",     "-",    "64-65",  "-"),
    ("Physical Barrier To Overcome",                    "68-69",  "-",     "-",     "-",     "-"),
    ("Injustice",                                         "-",    "-",     "-",    "66-67",  "-"),
    ("Quiet Catastrophe",                                 "-",   "71",     "-",     "-",     "-"),
    ("An Object Of Unknown Use Is Found",                 "-",    "-",    "75",     "-",     "-"),
    ("It's All About You",                                "-",    "-",     "-",     "-",    "64-65"),
    ("A Celebration",                                     "-",    "-",     "-",    "68-69",  "-"),
    ("Standoff",                                          "-",   "72",     "-",    "70",     "-"),
    ("Double Down",                                     "70-71",  "-",     "-",     "-",     "-"),
    ("Hidden Threat",                                     "-",   "73",     "-",     "-",     "-"),
    ("Character Connection",                              "-",    "-",     "-",     "-",    "66-67"),
    ("Religion",                                          "-",    "-",     "-",    "71",     "-"),
    ("Innocent",                                          "-",    "-",     "-",    "72",    "68"),
    ("Clear The Record",                                  "-",    "-",    "76",     "-",     "-"),
    ("Willing To Talk",                                   "-",    "-",     "-",     "-",    "69-70"),
    ("Theft",                                           "72-73",  "-",     "-",     "-",     "-"),
    ("Character Harm",                                    "-",    "-",     "-",     "-",    "71-72"),
    ("A Need To Hide",                                    "-",   "74-75",  "-",     "-",     "-"),
    ("Followed",                                          "-",   "76-77",  "-",     "-",     "-"),
    ("Framed",                                            "-",    "-",    "77",     "-",    "73"),
    ("Preparation",                                       "-",    "-",     "-",    "73-74", "74-75"),
    ("An Improbable Crime",                               "-",    "-",    "78",     "-",     "-"),
    ("Friend Focus",                                      "-",    "-",     "-",     "-",    "76"),
    ("Untouchable",                                       "-",    "-",     "-",     "-",    "77"),
    ("Bribe",                                             "-",    "-",     "-",     "-",    "78"),
    ("Dealing With A Calamity",                         "74-75",  "-",     "-",     "-",     "-"),
    ("Sudden Cessation",                                "76-77",  "-",     "-",     "-",     "-"),
    ("It's A Trap!",                                      "-",   "78-79",  "-",     "-",     "-"),
    ("A Meeting Of Minds",                                "-",    "-",     "-",    "75",     "-"),
    ("Time Limit",                                        "-",   "80-81",  "-",     "-",     "-"),
    ("The Hidden Hand",                                   "-",    "-",    "79-80",  "-",     "-"),
    ("A Needed Resource Is Running Short",                "-",   "82-83",  "-",     "-",     "-"),
    ("Organizations In Conflict",                         "-",    "-",     "-",    "76",     "-"),
    ("Bad News",                                          "-",   "84-85",  "-",     "-",     "-"),
    ("Character Assistance",                              "-",    "-",     "-",     "-",    "79-80"),
    ("Asking For Help",                                   "-",    "-",     "-",     "-",    "81-82"),
    ("Hunker Down",                                       "-",   "86",     "-",     "-",     "-"),
    ("Abandoned",                                         "-",   "87-88",  "-",     "-",     "-"),
    ("Find It Or Else",                                   "-",    "-",    "81-82",  "-",     "-"),
    ("Used Against Them",                               "78",    "89",     "-",     "-",     "-"),
    ("Powerful Person",                                   "-",    "-",     "-",    "77",     "-"),
    ("Creepy Tone",                                       "-",   "90-91",  "-",     "-",     "-"),
    ("Welcome To The Plot",                               "-",    "-",     "-",     "-",    "83"),
    ("Travel Setting",                                 "79",    "92",    "83",    "78",     "-"),
    ("Escort Duty",                                       "-",    "-",     "-",    "79",     "-"),
    ("An Old Deal",                                       "-",    "-",    "84",    "80",     "-"),
    ("A New Enemy",                                       "-",   "93",     "-",     "-",     "-"),
    ("Alliance",                                          "-",    "-",     "-",    "81-82",  "-"),
    ("Power Over Others",                                 "-",    "-",     "-",    "83-84",  "-"),
    ("A Mysterious New Person",                           "-",    "-",    "85",     "-",     "-"),
    ("Frenetic Activity",                               "80-81",  "-",     "-",     "-",     "-"),
    ("Rural Setting",                                     "-",   "94",    "86",    "85",     "-"),
    ("Likeable",                                          "-",    "-",     "-",     "-",    "84"),
    ("Someone Is Where They Should Not Be",               "-",    "-",    "87-88",  "-",     "-"),
    ("Sneaky Barrier",                                  "82-83",  "-",     "-",     "-",     "-"),
    ("Corruption",                                        "-",    "-",     "-",    "86-87",  "-"),
    ("Vulnerability Exploited",                           "-",   "95",    "89",     "-",     "-"),
    ("The Promise Of Reward",                             "-",    "-",     "-",     "-",    "85-86"),
    ("Fraud",                                             "-",    "-",    "90-91",  "-",     "-"),
    ("It's Business",                                     "-",    "-",     "-",    "88-89",  "-"),
    ("Just Cause Gone Awry",                              "-",    "-",     "-",    "90",     "-"),
    ("Expert Knowledge",                                  "-",    "-",     "-",     "-",    "87"),
    ("A Moment Of Peace",                               "84-85",  "-",     "-",     "-",     "-"),
    ("A Focus On The Mundane",                            "-",    "-",     "-",     "-",    "88-89"),
    ("Run Away!",                                         "-",    "-",     "-",     "-",    "90-91"),
    ("Beat You To It",                                  "86-87",  "-",    "92-93",  "-",     "-"),
    ("Confrontation",                                   "88-89",  "-",     "-",    "91",     "-"),
    ("Argument",                                          "-",    "-",     "-",    "92-93",  "-"),
    ("Social Tension Set To Boiling",                     "-",    "-",     "-",    "94",     "-"),
    ("Protector",                                       "90-91",  "-",     "-",     "-",    "92-93"),
    ("Crescendo",                                       "92-93",  "-",     "-",     "-",     "-"),
    ("Destroy The Thing",                               "94-95",  "-",     "-",     "-",     "-"),
    ("Conspiracy Theory",                                 "-",    "-",    "94",     "-",     "-"),
    ("Servant",                                           "-",    "-",     "-",    "95",    "94-95"),
    ("An Opposing Story",                                 "-",    "-",    "95",     "-",     "-"),
]

# Plot Points that CALL FOR A CHARACTER to be Invoked (The Adventure Crafter, "Character Crafting":
# many Plot Points reference a Character → roll the Characters List; a New result generates one).
# Curated from the names: any that designate a specific person, NPC role, or organization (AC treats
# organizations AS Characters), or an act whose subject/object is necessarily a Character. Editable —
# build_data.py bakes a "char": true flag onto these entries; the turning-point generator then flags
# each one inline and auto-invokes the Characters List.
CHAR_PLOT_POINTS = frozenset({
    "A Character Is Attacked In A Non-Lethal Way", "A Character Is Attacked In A Lethal Way",
    "A Character Is Attacked To Abduct", "A Character Disappears", "A Character Is Incapacitated",
    "A Character Acts Out Of Character", "A Character Is Diminished", "Character Has A Clever Idea",
    "Character Connection Severed", "Character Connection", "Character Harm", "Character Assistance",
    "Outcast", "An Organization", "People Behaving Badly", "Betrayal!", "Scapegoat", "The Observer",
    "Liar!", "Dead", "A Figure From The Past", "Enemies", "Sole Survivor", "Not Their Master",
    "The Leader", "Savior", "Servant", "Innocent", "Friend Focus", "Protector", "Powerful Person",
    "A New Enemy", "A Mysterious New Person", "Someone Is Where They Should Not Be", "The Hidden Hand",
    "Government", "Organizations In Conflict", "Reinforcements", "Help Is Offered, For A Price",
    "Willing To Talk", "Welcome To The Plot", "Alliance", "Suspicion", "Hunted", "Rescue",
    "Escort Duty", "At Your Mercy", "Family Matters",
})
