#!/usr/bin/env python3
"""
_arts_gyre_atlas.py — named Arts for the six Gyre traditions (11-Arts-of-the-Gyre.md)
and the four Atlas partial classes (Atlas 04-Optional-Rules-and-Classes.md).

Imported by build_magic.py so spells.json carries a real, pickable art per class
(type "<Tradition> Art"), instead of only a page pointer. Same record shape as
build_magic.py's own ELEMENTALIST_ARTS etc.: name -> dict(effort, action, effect,
dice, line). `line` indexes the class's source chapter (set per-tradition in
build_magic.TRAD_CHAPTER).

Notes:
- Adunic Invoker has NO arts of its own (it is a spell-point High Magic caster);
  it is wired via spell_lists=["High Magic"], not here.
- The Wise use NO Effort pool (every art effort="—"); their arts are constant or
  per-day/per-circumstance.
- "A Thousand Tongues" appears in both Bard and Blood Priest; build_magic.py keys
  the later one as "<name> (<Tradition>)" to avoid clobbering.
"""

# ===========================================================================
# GYRE TRADITIONS (11-Arts-of-the-Gyre.md)
# ===========================================================================
SKINSHIFTER_ARTS = {
    "Change Form": dict(effort="Day", action="Main",
        effect="Commit Effort for the day to transform into a mastered alternate form until you die, shift again, or end it (On Turn); HP/Strain/scores carry over, base attack bonus is at least the form's Form Bonus, and a quadruped's Move is +10'. (L1 free art.)",
        dice="—", line=138),
    "Eyes of the Hawk": dict(effort="—", action="Passive",
        effect="This form has acute senses: scent trails, hear faint noises, identify faces at 1,000', see in all but total darkness; +2 to sensory Notice checks.",
        dice="—", line=142),
    "Feline Leap": dict(effort="—", action="Move",
        effect="As a Move action, jump your full Move horizontally (or half vertically); subtract your Move from fall distance for fall damage.",
        dice="—", line=144),
    "Feral Prowess": dict(effort="—", action="Passive",
        effect="Pick Str/Dex/Con for this form; +1 to that modifier (max +2). Obvious alteration (can't pass as human); Con-gained HP lost on shifting back.",
        dice="—", line=146),
    "Intrinsic Armor": dict(effort="—", action="Passive",
        effect="This form has natural armor: base AC 14 + half level (round down), modifiable by Dex and a shield if the form can hold one.",
        dice="—", line=148),
    "Manifest Wings": dict(effort="—", action="Passive",
        effect="This form grows wings; can't attack while staying aloft, but fly at Move +10'/action, up to 10 miles/hour and 5 hours/day overland.",
        dice="—", line=150),
    "Octopus' Embrace": dict(effort="—", action="Passive",
        effect="This form has 4+ usable limbs; hold up to four Stowed objects Ready free of Readied Encumbrance. No extra attacks/shields/focus-actions.",
        dice="—", line=152),
    "Perfect Mimicry": dict(effort="—", action="Passive",
        effect="This form can exactly duplicate a specific creature given hair, a fresh blood drop, or 10 minutes' close observation; no further samples once learned.",
        dice="—", line=154),
    "Pliant Flesh": dict(effort="—", action="On Turn",
        effect="Change Form becomes usable On Turn (1/round) or as a 1-minute Effort-free shift; spending Effort to shift heals 1d6 + level. Intrinsic (free of form art limits).",
        dice="1d6+level", line=156),
    "Savage Talons": dict(effort="—", action="Passive",
        effect="Natural weapons 1d8 (Str/Dex, Punch, Shock 2/AC 13) that harm creatures immune to non-magical weapons; +1 dmg/Shock at L3, +2 at L6, +3 at L9.",
        dice="1d8", line=158),
    "Sculptor's Beauty": dict(effort="—", action="Passive",
        effect="This form improves Charisma modifier by +1 (max +2) via uncanny beauty; always something alien, so it can't pass as wholly normal.",
        dice="—", line=160),
    "Serpent's Kiss": dict(effort="Scene", action="Instant",
        effect="On a hit, Commit Effort for the scene (Instant) for an extra 1d8 + Survive; optionally paralytic, leaving foes dropped to 0 HP helpless an hour instead of mortally wounded.",
        dice="1d8+Survive", line=162),
    "The Monkey's Road": dict(effort="—", action="Passive",
        effect="This form climbs sheer (non-glassy) surfaces at normal Move with three limbs free; halts a fall without damage if a graspable surface is within 10'.",
        dice="—", line=164),
    "Warform": dict(effort="—", action="Passive",
        effect="+2 to all melee hit rolls in this form, usable even in a humanoid body; blatantly martial (can't pass as harmless).",
        dice="—", line=166),
    "Wisdom of Fin and Scale": dict(effort="—", action="Passive",
        effect="This form breathes water, swims at double Move, ignores cold/pressure, sees 60' underwater without light.",
        dice="—", line=168),
}

KISTIAN_ARTS = {
    "Favored Weapon": dict(effort="—", action="Passive",
        effect="Choose one non-unarmed melee weapon type; use the Duelist Favored-Weapon hit-bonus column (or =level if your other class is Partial Warrior). Not for thrown weapons. (L1 free art.)",
        dice="—", line=224),
    "Blood for Blood": dict(effort="Scene", action="Instant",
        effect="Commit Effort (Instant) when an enemy lands a physical hit on you; if you strike that foe with your favored weapon before next round ends, the blow hits automatically for no less than the damage dealt to you (up to weapon max).",
        dice="—", line=228),
    "Burst of Speed": dict(effort="Day", action="On Turn",
        effect="Commit Effort for the day (On Turn) to move your full Move as an On Turn action; once per round.",
        dice="—", line=230),
    "Code Duello": dict(effort="Day", action="On Turn",
        effect="Commit Effort for the day (On Turn) against one foe; while no one else attacks you/your target and you attack only it, gain +4 AC and roll hit rolls twice, better result. Disrupted = can't reinvoke that scene.",
        dice="—", line=232),
    "Crushing Superiority": dict(effort="Scene", action="Instant",
        effect="Favored weapon gains Less Lethal; Commit Effort (Instant) on a hit to force an Instinct check. Once/scene per target.",
        dice="—", line=234),
    "Dauntless Step": dict(effort="Scene", action="On Turn",
        effect="Commit Effort for the scene (On Turn); your Move this round may cross vertical surfaces/difficult terrain at full Move if you end upright on a weight-bearing surface.",
        dice="—", line=236),
    "Dodge Doom": dict(effort="Day", action="Instant",
        effect="Commit Effort for the day (Instant) when caught in a blast; take half damage (none if it allows a save you pass) and move up to 10' to cover or away from the origin.",
        dice="—", line=238),
    "Forced Engagement": dict(effort="Scene", action="Instant",
        effect="Commit Effort (Instant) when attacking with your favored weapon to ignore one foe's Screen Ally for that attack.",
        dice="—", line=240),
    "Gentleman's Withdrawal": dict(effort="Scene", action="Move",
        effect="Commit Effort (Move) to move your full rate unhindered by armed foes (unless they fully block you), as a Fighting Withdrawal against all engaged enemies.",
        dice="—", line=242),
    "Graceful Leap": dict(effort="Scene", action="On Turn",
        effect="Commit Effort (On Turn) to leap up to 10' as a Fighting Withdrawal; once/round, not after attacking. Immune to falling damage under 30'.",
        dice="—", line=244),
    "Lightning Draw": dict(effort="Day", action="Instant",
        effect="Commit Effort for the day (Instant) at the start of hostilities; win initiative vs anyone lacking a like ability and ready a Stowed favored weapon Instantly.",
        dice="—", line=246),
    "Piercing Strike": dict(effort="Scene", action="On Turn",
        effect="Commit Effort (On Turn) to mark a visible target; for the scene its AC counts as 10 vs your favored weapon's Shock.",
        dice="—", line=248),
    "Spiritual Weapon": dict(effort="Indefinite", action="Instant",
        effect="After translating a favored weapon to a spiritual template (destroying the physical form), Commit Effort (Instant) to manifest a Readied ghostly copy until released; dual-wielders summon two with one use.",
        dice="—", line=250),
    "Unbindable": dict(effort="Day", action="On Turn",
        effect="Commit Effort for the day (On Turn) to wriggle free of mundane bindings and gain an Evasion save to end a magical physical binding; once/round.",
        dice="—", line=252),
    "Unworthy Rabble": dict(effort="Day", action="On Turn",
        effect="Commit Effort for the day (On Turn); for the scene, reroll failed favored-weapon hit rolls vs 1-HD foes (2-HD at L8).",
        dice="—", line=254),
    "Whirling Evasion": dict(effort="—", action="Passive",
        effect="Base AC becomes 13 + half level (round up), modifiable by small shields and Dex but not armor or large shields.",
        dice="—", line=256),
}

BEASTMASTER_ARTS = {
    "Bind Companion": dict(effort="—", action="Main",
        effect="With a day's work, find and bind an animal companion (Wis/Survive vs 10+ for rare beasts); one met on adventure is bound as a Main Action (it gets a Mental save to resist and become immune). Release as a Main Action. (L1 free art.)",
        dice="—", line=310),
    "Beast Ward": dict(effort="Indefinite", action="On Turn",
        effect="Commit Effort (On Turn); while Committed, unintelligent beasts won't attack you unless commanded, starving, or provoked. Broken = no reactivation that scene; magical/trained beasts get a Mental save.",
        dice="—", line=314),
    "Eyes of the Beast": dict(effort="Scene", action="On Turn",
        effect="Commit Effort for the scene (On Turn) to share your companion's senses; neither of you can be surprised unless both are.",
        dice="—", line=316),
    "Feral Toughness": dict(effort="—", action="Passive",
        effect="Max HP +companion's natural HD; ignore outdoor heat/cold extremes; base AC 13 + half level (round up), modifiable by shields/Dex but not armor.",
        dice="—", line=318),
    "Howl of Distant Summons": dict(effort="Day", action="Main",
        effect="Commit Effort for the day (Main) to call a former companion to reach you within five minutes; a dangerous/long trip needs Cha/Survive vs 10+, failure means no recall for a week.",
        dice="—", line=320),
    "Know the Weak Spot": dict(effort="Scene", action="Instant",
        effect="Roll damage twice (take higher) when harming a beast; optionally Commit Effort (Instant) to let an ally who hits a beast roll damage twice too.",
        dice="—", line=322),
    "Mind Call": dict(effort="Scene", action="On Turn",
        effect="Commit Effort for the scene (On Turn) to forge a telepathic bond with your companion, giving orders and receiving info within its intellect.",
        dice="—", line=324),
    "Natural Weaponry": dict(effort="—", action="Passive",
        effect="Unarmed attacks count as weapons (Str/Dex, Punch/Stab) doing 1d8, Shock 2/AC 13, harming creatures immune to non-magical weapons; +1 dmg/Shock at L3, +2 at L6, +3 at L9.",
        dice="1d8", line=326),
    "Savage Senses": dict(effort="Scene", action="On Turn",
        effect="Commit Effort for the scene (On Turn); see in pitch dark, scent trails/belongings like a wolf, +2 to sight/sound/smell Notice checks.",
        dice="—", line=328),
    "Shared Vitality": dict(effort="Scene", action="Instant",
        effect="Bound companions have HD no lower than your level (hit bonus >= half HD); Commit Effort (Instant) to stabilize a Mortally Wounded companion.",
        dice="—", line=330),
    "Swift Healing": dict(effort="Day", action="Main",
        effect="Commit Effort for the day (Main) to heal a companion 1d6 per character level; once per scene/fifteen minutes.",
        dice="1d6/level", line=332),
    "Tongue of the Beasts": dict(effort="Indefinite", action="On Turn",
        effect="Commit Effort (On Turn); while Committed, speak with any furred/feathered/scaled/skinned animal, granting it temporary humanlike intellect to converse (desires unchanged).",
        dice="—", line=334),
}

BLOODPRIEST_ARTS = {
    "A Thousand Tongues": dict(effort="Indefinite", action="On Turn",
        effect="Commit Effort (On Turn); while Committed, speak with and understand any sentient with a language, seeming fluent while you speak your own tongue. No reading/writing of unknown scripts.",
        dice="—", line=386),
    "Armor of God": dict(effort="Indefinite", action="On Turn",
        effect="Commit Effort (On Turn); while Committed, natural AC 15 + half level (round down), modifiable by shields/Dex but not worn armor.",
        dice="—", line=388),
    "Divine Guidance": dict(effort="Day", action="Main",
        effect="Commit Effort for the day (Main) to meditate on a choice; GM states weal/woe/mixed/nothing, looking ~an hour ahead.",
        dice="—", line=390),
    "Fear No Flame": dict(effort="Day", action="On Turn",
        effect="Commit Effort for the day (On Turn) on a target; for the scene immune to non-magical flame/smoke/explosive damage and reduce magical fire by 5 per Pray level.",
        dice="—", line=392),
    "God Wills It": dict(effort="Day", action="Instant",
        effect="Commit Effort for the day (Instant); for the scene up to six allies/level in earshot gain Morale 12 and +1 hit & damage (incl. Shock); +2 at L5, +3 at L10.",
        dice="—", line=394),
    "Merciful Healing": dict(effort="Day", action="Main",
        effect="Commit Effort for the day (Main) and touch a target for 1d6+2 healing (2d6+4 at L4, 4d6+8 at L8); reviving the Mortally Wounded or healing in combat adds 1 Strain.",
        dice="1d6+2", line=396),
    "Sanctified Ward": dict(effort="Indefinite", action="On Turn",
        effect="Commit Effort (On Turn); while maintained and until you act hostilely, immune to Shock, +4 AC and +4 saves, and foes need an Instinct check to target you. Ended = no reactivation that scene; healing isn't hostile.",
        dice="—", line=398),
    "Smite the Wicked": dict(effort="Day", action="On Turn",
        effect="Commit Effort for the day (On Turn) attacking one target: +4 to hit, inflict your level as automatic damage, and roll damage dice twice (take higher). Once/scene per target.",
        dice="—", line=400),
    "The Light of Faith": dict(effort="Indefinite", action="On Turn",
        effect="Commit Effort (On Turn); while Committed, cast bright radiance up to 30', optionally visible only to you and up to a dozen allies.",
        dice="—", line=402),
    "Transubstantiation": dict(effort="Day", action="Main",
        effect="Commit Effort for the day (Main) to turn up to a gallon of liquid into sacred blood; a draught sustains a day without food/water and heals 1d6 + Pray (a gallon ~six people). Once/day; undrunk blood sublimates in a minute.",
        dice="1d6+Pray", line=404),
    "Turn False Life": dict(effort="Day", action="Main",
        effect="Commit Effort for the day (Main) vs targets within 60'; roll 2d6 + level of affected undead/automaton/unnatural HD, which save (Mental) or cower for the scene. No effect on foes with twice your HD.",
        dice="2d6+level", line=406),
    "Words of Mercy": dict(effort="Day", action="Instant",
        effect="Commit Effort for the day (Instant) to reroll a failed social check tied to peace, aid, or compassion/mercy/truth; once per check.",
        dice="—", line=408),
    "Wrath of the Most High": dict(effort="Scene", action="Main",
        effect="Commit Effort for the scene (Main) to rebuke a visible target; the first time it takes damage before next round ends, it suffers +1d8 + level automatic damage.",
        dice="1d8+level", line=410),
}

THOUGHTNOBLE_ARTS = {
    "Open Mind": dict(effort="Indefinite", action="On Turn",
        effect="Commit Effort (On Turn); while Committed, detect a visible living creature's current emotional state as a Main Action (not fine enough to identify the emotion's object unless obvious). (L1 free art.)",
        dice="—", line=432),
    "Block Memory": dict(effort="Day", action="Main",
        effect="Commit Effort for the day (Main) vs a visible creature and a scene-or-shorter event; Mental save or it forgets and confabulates. Detecting the change is +2 difficulty; restorable.",
        dice="—", line=438),
    "Elicitation of Truth": dict(effort="Day", action="Main",
        effect="Requires Surface Apprehension. Only on a helpless/cooperative target; Commit Effort for the day and ask a <=2-sentence question; Mental save or it must answer fully without conscious deceit.",
        dice="—", line=440),
    "Facile Speech": dict(effort="—", action="On Turn",
        effect="Enhances Far Speech: nominate up to six companions as favored targets you link to (On Turn) without Committing Effort, range one mile/level. Change nominees with an hour's meditation.",
        dice="—", line=458),
    "Far Speech": dict(effort="Scene", action="On Turn",
        effect="Commit Effort for the scene (On Turn) on a known intelligent creature within 200'/level; with consent, a telepathic link conveys thought/speech/images without a shared language. While linked, both reroll failed Mental saves and can't be surprised unless both are.",
        dice="—", line=462),
    "Hypercognition": dict(effort="Day", action="Instant",
        effect="Eidetic memory and advanced mental calculation; Commit Effort for the day (Instant) to reroll a failed Int-based check. Once per check.",
        dice="—", line=464),
    "Iconograph": dict(effort="Scene", action="Main",
        effect="Commit Effort for the scene (Main) on a visible text/symbol/artifact to read the maker's intended message; or imbue your own so valid viewers grasp your meaning (audience-restrictable).",
        dice="—", line=466),
    "Impress Imperative": dict(effort="Day", action="Main",
        effect="Commit Effort for the day (Main) on a visible living creature, giving an overwhelming urge to perform a round-long action not wholly against its nature; Mental save or it obeys next action.",
        dice="—", line=468),
    "Mind Light": dict(effort="—", action="Passive",
        effect="Enhances Open Mind: sense all living minds within 60' (barring barriers/hiding), identify species/strong emotions, recognize known individuals, and never be surprised by a living creature.",
        dice="—", line=470),
    "Mind Over Matter": dict(effort="Day", action="Instant",
        effect="Commit Effort for the day (Instant) for one: auto-stabilize if Mortally Wounded, 24h without sleep, heal 1d6 HP, or ignore climatic extremes for a day.",
        dice="1d6", line=472),
    "Mirror Mask": dict(effort="Day", action="Instant",
        effect="Sense any mind-affecting power aimed at you and identify a user in range; reroll any Mental save it allows (or get one). On success, Commit Effort for the day (Instant) to feed it false info/feigned success.",
        dice="—", line=474),
    "Positive Association": dict(effort="Day", action="Main",
        effect="Commit Effort for the day (Main) on a visible sentient; Mental save or it treats you as an admired friend and finds your acts reasonable until you/allies harm it or what it loves, or you leave 1+ hour. One target at a time.",
        dice="—", line=478),
    "Read Intent": dict(effort="Scene", action="Instant",
        effect="Commit Effort for the scene (Instant) on a visible living creature; Mental save or the GM tells you its next intended action. If you take Total Defense this round, no avoidable attack it makes can hit you.",
        dice="—", line=480),
    "Surface Apprehension": dict(effort="Scene", action="Main",
        effect="Commit Effort for the scene (Main) on a visible living creature; Mental save or you read its surface thoughts this round, and your questions make it instinctively think of brief answers.",
        dice="—", line=482),
    "Thoughts Like Razors": dict(effort="Day", action="Main",
        effect="Commit Effort for the day (Main) on a visible living creature within 60'; Mental save or 1d8 per Thought Noble level (can KO, not kill). On a save you're stunned, take a quarter damage, lose next turn. Once/scene.",
        dice="1d8/level", line=484),
    "Unthinkable Thought": dict(effort="Day", action="Main",
        effect="Commit Effort for the day (Main) on a visible living creature, naming a present person/object/situation; Mental save or it can't consciously acknowledge that subject (unless ignoring risks its life) for up to a scene, with no memory after.",
        dice="—", line=486),
}

# ===========================================================================
# ATLAS PARTIAL CLASSES (04-Optional-Rules-and-Classes.md)
# Effort: Accursed = Magic + best Int/Cha; Bard = Perform + Cha;
# Mageslayer = Magic + best Int/Con (arts FIXED by level); Wise = NO Effort.
# ===========================================================================
ACCURSED_ARTS = {
    "Accursed Blade": dict(effort="—", action="On Turn",
        effect="Manifest an occult melee weapon (1d8 one-handed / 2d6 two-handed) adding Magic to damage, Shock 2/15; attacks use Magic and best of Str/Dex/Int/Cha. Usable in or out of armor. (L1 free choice with Accursed Bolt.)",
        dice="1d8 or 2d6 +Magic", line=477),
    "Accursed Bolt": dict(effort="—", action="On Turn",
        effect="As Accursed Blade but a ranged occult blast: 1d8 + Magic, 200' range, throwable in melee at -4; needs both hands free. (L1 free choice with Accursed Blade.)",
        dice="1d8 +Magic", line=479),
    "Bewitching Distraction": dict(effort="Day", action="Main",
        effect="Out of combat, target an intelligent creature you're talking to; Mental save or it's dazed and forgets you and the scene. Danger ends the daze, not the forgetting.",
        dice="—", line=481),
    "Compelling Shriek": dict(effort="Day", action="Main",
        effect="Once/scene, shout a <=7-word command; chosen targets who hear and understand make a Mental save or obey one round, unless wholly against their character.",
        dice="—", line=483),
    "Devil's Bargain": dict(effort="—", action="Main",
        effect="Consecrate a deal made with an uncoerced person; if they break it or its spirit you know instantly and may deal 1d6/level to them.",
        dice="1d6/level", line=485),
    "Dire Pact": dict(effort="—", action="Passive",
        effect="Foes take a penalty equal to your Magic skill on saves vs your Accursed arts; if a foe still succeeds, you gain 1 System Strain.",
        dice="—", line=487),
    "Lying Face": dict(effort="Indefinite", action="Main",
        effect="While Committed, disguise yourself as any humanoid of similar size, matching clothing, scent, and voice.",
        dice="—", line=489),
    "Night-Black Eyes": dict(effort="—", action="Main",
        effect="See in perfect darkness; as a Main Action, focus on a visible object/person/place to learn whether it's enchanted (no detail).",
        dice="—", line=491),
    "Pacted Protection": dict(effort="—", action="Passive",
        effect="Choose an energy type; immune to natural amounts and half damage from magical attacks of that type.",
        dice="—", line=493),
    "Rob Vitality": dict(effort="Scene", action="On Turn",
        effect="Once/scene, target a visible foe; Physical save or it loses its next Main Action, which you immediately gain.",
        dice="—", line=495),
    "Scourging Curse": dict(effort="Scene", action="Main",
        effect="Curse a visible foe with -1 (-2 at L4, -3 at L9) to hit, damage, and saves for one round/level; one such curse active at a time.",
        dice="—", line=497),
    "Shadowed Steps": dict(effort="Scene", action="Move",
        effect="Teleport up to your Move (incl. upward), but not through walls/obstacles.",
        dice="—", line=516),
    "Snaring Speech": dict(effort="Day", action="Instant",
        effect="Once/round, when you fail to persuade/tempt someone, Mental save or they agree if it's something they'd consider. Gain 1 Strain.",
        dice="—", line=518),
    "Sorcerous Battery": dict(effort="Day", action="On Turn",
        effect="Once/day, you or a visible ally refresh a spell slot used since the prior round's start. Gain 1 Strain.",
        dice="—", line=520),
    "Soul Consumption": dict(effort="Day", action="Instant",
        effect="When you fell an intelligent target with Accursed Blade/Bolt, it dies instantly; you heal 1d6+level and lose 1 accumulated Strain.",
        dice="1d6+level", line=522),
    "Tendrils of Night": dict(effort="Indefinite", action="On Turn",
        effect="While Committed, eldritch tentacles manipulate objects at your Str up to 20' and melee at range; no bonus actions; arms share your AC and harm to them harms you.",
        dice="—", line=524),
    "Unseen Steps": dict(effort="Day", action="On Turn",
        effect="Turn invisible 1d6+level rounds; breaks when you attack, cast, or act violently.",
        dice="1d6+level", line=526),
    "Weight of Sin": dict(effort="Day", action="Main",
        effect="Target a visible foe; Physical save or it loses its Move action for 1d6+level rounds.",
        dice="1d6+level", line=528),
    "Weeping Wounds": dict(effort="Scene", action="Instant",
        effect="Once/round, when a visible enemy takes damage, Physical save or 1d6/round for one round/level, unhealable during it. No stack.",
        dice="1d6/round", line=530),
}

BARD_ARTS = {
    "A Thousand Tongues": dict(effort="—", action="Passive",
        effect="Communication arts are understood by all intelligent creatures regardless of language; learn a new language with a week's study with a native speaker. (L1 free art.)",
        dice="—", line=602),
    "Battle Cry": dict(effort="Day", action="On Turn",
        effect="Bolster allies: +1 (+2 at L4, +3 at L9) to hit, saves, and damage (incl. Shock) for one round/level.",
        dice="—", line=604),
    "Cursed Tune": dict(effort="Scene", action="Main",
        effect="Target an intelligent creature: -1 (-2 at L4, -3 at L9) to hit, damage, and saves for one round/level.",
        dice="—", line=606),
    "Deft Fingers": dict(effort="—", action="Passive",
        effect="Your maximum Readied item count increases by two.",
        dice="—", line=608),
    "Entangle Incantation": dict(effort="Scene", action="Instant",
        effect="When a foe within 60' incants a spell, opposed Int/Magic vs your Cha/Perform +2; tie/win and the spell fizzles. Once/round.",
        dice="—", line=610),
    "Evoke Emotion": dict(effort="Day", action="Main",
        effect="While performing (not combat, once/scene), evoke an emotion granting you and allies +1 to relevant social checks for the scene; optionally force a new Reaction Roll, keeping it if better.",
        dice="—", line=612),
    "Inspire Dread": dict(effort="Day", action="Instant",
        effect="When enemies make a Morale check, force them to roll twice; any passing both must immediately make an Instinct check.",
        dice="—", line=616),
    "Keen Senses": dict(effort="—", action="Passive",
        effect="Sight-equivalent perception to 60' even if blinded (no color); invisible creatures/objects are obvious to you.",
        dice="—", line=632),
    "Liberating Song": dict(effort="Scene", action="Instant",
        effect="Immune to mind/emotion control; grant an ally a Mental save to throw off such an effect (if it allowed one). A failed second save can't be retried.",
        dice="—", line=634),
    "Rally": dict(effort="Day", action="Main",
        effect="Exhort a wounded/fallen ally, removing Frailty and restoring 2d6+level HP; you incur 1 Strain.",
        dice="2d6+level", line=636),
    "Soothe the Savage": dict(effort="Day", action="Main",
        effect="While you perform each round (Main), animals/bestial creatures won't attack you or allies unless commanded or threatened; can't start once combat has begun.",
        dice="—", line=638),
    "Soothing Graces": dict(effort="—", action="Passive",
        effect="You and allies lose an extra System Strain after each night's comfortable rest; no stack with similar rest powers.",
        dice="—", line=640),
    "Swift Misdirection": dict(effort="Scene", action="Main",
        effect="Tell one creature in earshot a one-sentence claim; unless impossible/unendurable, Mental save or it believes it one round. Once/creature/scene.",
        dice="—", line=642),
}

MAGESLAYER_ARTS = {
    "Antimage": dict(effort="—", action="Passive",
        effect="Gain one level of the Nullifier Focus free (or a free Focus if you already have both Nullifier levels). (Fixed art, L1.)",
        dice="—", line=701),
    "Magebane": dict(effort="—", action="Passive",
        effect="Add half your level (round up) to all damage you deal to casters by any means. Doesn't stack with Killing Blow. (Fixed art, L1.)",
        dice="+half level", line=727),
    "Witchfinder": dict(effort="Scene", action="Main",
        effect="For the scene, gain Apprehend the Arcane Form's benefits except its dark-vision. (Fixed art, L2.)",
        dice="—", line=735),
    "Spellshield": dict(effort="—", action="Passive",
        effect="HP damage from a spell is automatically halved (round down) before saves or resistances. (Fixed art, L2.)",
        dice="—", line=731),
    "Disrupt Sorcery": dict(effort="Scene", action="On Turn",
        effect="Your next attack that round (even on a miss) leaves the target unable to cast or trigger Mage arts the rest of the round; negated if an ally Screens it. (Fixed art, L3.)",
        dice="—", line=705),
    "Know Your Prey": dict(effort="—", action="Passive",
        effect="Treat Magic skill as one higher (max 4), adding to Effort and possibly above the normal cap. (Fixed art, L4.)",
        dice="—", line=725),
    "Share the Pain": dict(effort="Day", action="Instant",
        effect="When targeted by/in the area of a hostile spell, Mental save; success treats the caster as also affected. Once/round. (Fixed art, L5.)",
        dice="—", line=729),
    "Dispel Enchantment": dict(effort="Day", action="Main",
        effect="Touch an ally/self to act as Extirpate Arcana; creatures only, once/day per target. (Fixed art, L6.)",
        dice="—", line=703),
    "Ward Ally": dict(effort="Scene", action="Instant",
        effect="When an ally within 30' is affected by a spell, you take it instead (twice if you share the area); your anti-sorcery defenses still apply. (Fixed art, L7.)",
        dice="—", line=733),
    "Immaculate Body": dict(effort="—", action="Passive",
        effect="Magical transformations/curses/lingering penalties last at most one scene on you and can't kill you (1 HP min). (Fixed art, L8.)",
        dice="—", line=707),
    "Immaculate Mind": dict(effort="—", action="Passive",
        effect="Immune to unwanted mind-affecting/reading effects; auto see through illusions and magical invisibility. (Fixed art, L9.)",
        dice="—", line=723),
    "Absolute Negation": dict(effort="Day", action="Instant",
        effect="When about to be affected/impeded by an unwanted spell or standing spell-effect, simply ignore the magic. (Fixed art, L10.)",
        dice="—", line=699),
}

WISE_ARTS = {
    "Dread Awe": dict(effort="—", action="Main",
        effect="+1 to intimidation; once/scene (Main) curse foes in battle so those who hear take -1 on their next Morale check.",
        dice="—", line=776),
    "Elite Ties": dict(effort="—", action="Passive",
        effect="Readily get audiences with important figures; once/session a favor from them that wouldn't much inconvenience them.",
        dice="—", line=780),
    "Erudite": dict(effort="—", action="Passive",
        effect="Once/day, reroll a failed intellectual/scholarly skill check.",
        dice="—", line=782),
    "Folk-Friend": dict(effort="—", action="Passive",
        effect="Once/day, a modest favor from a commoner who doesn't hate you, for a blessing or advice.",
        dice="—", line=784),
    "Wise Healer": dict(effort="—", action="On Turn",
        effect="+1 to all Heal checks; once/day auto-succeed a check to stabilize a Mortally Wounded subject. (The Wise art 'Healer'.)",
        dice="—", line=786),
    "Holy Sanctity": dict(effort="—", action="Passive",
        effect="+1 to social checks with locals not naturally opposed to your religion or institution.",
        dice="—", line=788),
    "Personal Impunity": dict(effort="—", action="Passive",
        effect="Harming you is taboo here; only the vicious/desperate start violence on you, and hostile groups hesitate to attack your companions unless provoked.",
        dice="—", line=790),
    "Skilled": dict(effort="—", action="Passive",
        effect="Gain three non-combat skill points (up to your cap). May be taken more than once.",
        dice="—", line=792),
    "Compel Truth": dict(effort="—", action="Main",
        effect="After a scene-long ordeal, ask one question; GM secretly rolls Cha/Magic vs Morale+1 (level+6 for PCs); success forces a truthful answer. Same question can't be asked twice.",
        dice="—", line=796),
    "Deliver Oracle": dict(effort="—", action="Main",
        effect="A day's ritual on a course; GM secretly rolls Wis/Magic: diff 8 somewhat-true, diff 12 clear, 7- ambiguous, natural 2 misleading.",
        dice="—", line=800),
    "Find Object": dict(effort="—", action="Main",
        effect="A scene-long ritual to locate a known object/animal/substance (not people); Wis/Magic vs diff 8-11 by distance (>5 mi undetectable); success gives a direction. Once/day.",
        dice="—", line=826),
    "Read Omens": dict(effort="—", action="Main",
        effect="A scene-long ritual with 10+ sp sacrifice; Wis/Magic vs diff 10 to judge a course's success/failure; x10 sacrifice = +1. Same course once a month.",
        dice="—", line=832),
    "Auspicious Undertaking": dict(effort="—", action="Main",
        effect="Bless a target's current plan; during it they may reroll one failed check or one missed hit. Lasts until used or one day/level. One plan at a time.",
        dice="—", line=824),
    "Evil Eye": dict(effort="—", action="Passive",
        effect="Curse/blessing arts may be used as Instant actions (still one/round) and need only a look, not vocalization.",
        dice="—", line=828),
    "Ill Fate": dict(effort="—", action="Main",
        effect="Curse a visible target; their next relevant check takes -1, and if its raw die is <= your Magic +1 it goes disastrously wrong. Lasts until that check.",
        dice="—", line=830),
    "Luck Blessing": dict(effort="—", action="Main",
        effect="Bless a visible target so their next skill check that day gets +1; one luck blessing per creature at a time.",
        dice="—", line=834),
    "War Curse": dict(effort="—", action="Main",
        effect="Curse a visible enemy with -2 to hit, damage, and Shock for the scene; if they miss with a raw die below your Magic skill they hurt themselves. One war curse at a time.",
        dice="—", line=836),
}
